version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inumaki
    ports:
      - "5432:5432"
    volumes:
      - inumaki_pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inumaki
      - AUTH_TRUST_HOST=true

volumes:
  inumaki_pg_data:
